name: GitHub Actions Demo

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/**

  schedule:
    - cron: '15 6 * * 0'

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print data
        run: |
          echo 'The event triggering this workflow is ${{ github.event_name }}'
          echo 'The branch for this workflow is ${{ github.ref }}'
          echo 'The repository is ${{ github.repository }}'
        
      - uses: actions/checkout@v4
      - run: tree
